DROP TABLE IF EXISTS deltas;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS features;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS users;
DROP EXTENSION IF EXISTS "pgcrypto";